{{ if or (eq .Values.config.type "application") .Values.config.web }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        # add an annotation indicating the issuer to use.
        #    cert-manager.io/acme-challenge-type: http01
        #    cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    name: {{ .Values.config.name }}-{{ .Values.config.env }}-ingress
    labels:
        app.kubernetes.io/name: {{ .Values.config.name }}-ingress
        app.kubernetes.io/part-of: {{ .Values.config.name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    rules:
        - host: {{ $.Values.ingress.host }}
          http:
              paths:
                  - path: {{ $.Values.ingress.path }}/(.*)
                    backend:
                        serviceName: {{ $.Values.config.name }}
                        servicePort: 80
                  - path: {{ $.Values.ingress.path }}(.*)
                    backend:
                        serviceName: {{ $.Values.config.name }}
                        servicePort: 80
  {{ end }}
